### ISSUE TITLE
Code error in sensors module

### ISSUE THREAD

**Issue by IndyJoeA** [Manuel83/craftbeerpi3#11]
In the file [https://github.com/Manuel83/craftbeerpi3/blob/master/modules/sensors/__init__.py](https://github.com/Manuel83/craftbeerpi3/blob/master/modules/sensors/__init__.py) at line # 34, there appears to be a missing "e" in the function call, so I don't believe passive sensors are being read:

`@cbpi.backgroundtask(key="read_passiv_sensor", interval=5)`
`def read_passive_sensor():`

**Comment by carlallen** [comment]
the key is just the name of the background task, it doesn't have to mach the name of the method. Passive sensors are working just fine

**Comment by IndyJoeA** [comment]
Yes, thanks.. I meant to come back and close this by now.
