### ISSUE TITLE
Wifi signal in control box

### ISSUE THREAD

**Issue by chrisbrucewilliams** [Manuel83/craftbeerpi3#156]
I only have a bread board right now and my control box has not yet arrived.  I was wondering if the PI can receive a signal when it is inside the control box?  And if it cannot get a signal how have you solved this?  I was thinking I would either hardwire to the net or use a usb antenna on the outside of the box.

**Comment by Philusha1983** [comment]
My Control box is made of metal and without any external antenna the pi has
Wifi signal.
ᐧ


Philip   ;)

**Comment by chrisbrucewilliams** [comment]
Thanks. That is great to hear. Hope to test this over the weekend.
