### ISSUE TITLE
Auto mode does not work in Fermentation

### ISSUE THREAD

**Issue by helibrewer** [Manuel83/craftbeerpi3#16]
Manual switch operation functions normally.
Auto mode fahrenheit does not work for cooling
Auto mode fahrenheit does not work for heating
Auto mode celsius does not work for cooling
Auto mode celsius does not work for heating

Tried on GPIO pins 17 and 22 (both non-pwm)
Used GPIOSimple to set up switch actor
Deleted Craftbeerpi and completely reinstalled -- no change
Auto mode celsius heating works for Brewing

Verified hardware by using my Craftbeerpi 2.2 SD card and auto mode worked for Fermentation

**Comment by swimIan** [comment]
I am expierencing something similiar. Heating work on Celsius but not Fahrenheit. I did not test cooling.

**Comment by OliverE79** [comment]
I set up GPIO 18 as cooler (switches fridge by ssr).
The GPIO is never activated in auto mode, neither in hysteresis nor in pid mode. I am not sure if I configured  it correctly but I guess even with non optimal pid settings it should have switched at some point.

When adding a fermentation step the direction is displayed as "Heater", no matter if the temperature is below or above the setpoint. when I add a dummy actor and configure it as heater the direction seems to match - it starts to indicate "cool" also. But the GPIO is not activated.

**Comment by helibrewer** [comment]
I noticed this error in the log after selecting the "auto" button on the fermenter:
ERROR:modules.app_config:Exception in function heater_off. Return default None

**Comment by carlallen** [comment]
If you are using Fahrenheit and it's not working, that should be fixed by this PR https://github.com/Manuel83/craftbeerpi3/pull/24

Try again after updating.

**Comment by helibrewer** [comment]
In modules.modes.core.controller.py, the following lines look like errors. they show f.heater and I believe they should be f.cooler

Lines 132 and 144

**Comment by helibrewer** [comment]
Working after latest pulls

**Comment by helibrewer** [comment]
Working after latest pulls

**Comment by got2brew** [comment]
I had the same issue on a single fermenter...  Found the issue.  I had accidentally erased the '0' in the heater off section. This made the automate not work. Once I put the zero back in the box, the auto mode worked again. (even though I was not using a heater)
