### ISSUE TITLE
Option for custom background

### ISSUE THREAD

**Issue by KenCope** [Manuel83/craftbeerpi3#160]
I have attempted to write the code to change the background using the https://github.com/Manuel83/craftbeerpi3/blob/master/modules/ui/static/index.html file.  No success for me.  Can anyone help?  Manuel suggested some code for me, no success either.  Thanks in advance!

**Manuel suggested:

**_You need to add a custom css in this file.

https://github.com/Manuel83/craftbeerpi3/blob/master/modules/ui/static/index.html

Please add the following code in line 13

<style>
    body {
        background-image: url("static/bg.jpg") !important;
    }

</style>

The background image need to be placed in modules/ui/static/bg.jpg_****

**Comment by HooTsBrooklyn** [comment]
If you just add background-image:url('bg,jpg'); under the body declaration in the bootstrap.dark.css file, put the bg.jpg file in the ui/static/ folder and it'll work.
![virtualbox_raspberrypi clone_07_12_2017_18_26_45](https://user-images.githubusercontent.com/4926059/33745403-4da22a9a-db7c-11e7-88cf-ab925989653b.png)
![virtualbox_raspberrypi clone_07_12_2017_18_27_04](https://user-images.githubusercontent.com/4926059/33745404-4dc5d850-db7c-11e7-8860-f1ac15b9437d.png)
![virtualbox_raspberrypi clone_07_12_2017_18_28_31](https://user-images.githubusercontent.com/4926059/33745432-754b6822-db7c-11e7-9dce-eaff5130995e.png)

I un-minimized the CSS file for ease of reading though

**Comment by KenCope** [comment]
For some reason I can't get this to work.  I open the bootstrap.dark.css file using text editor, insert the verbiage you gave me and all it does is prints that on the screen in the background.  I appreciate everyone's help.

**Comment by KenCope** [comment]
[Image]

Is the file size of the.jpg limited?
________________________________

**Comment by HooTsBrooklyn** [comment]
Looks like I made a typo.  It should be bg.jpg not bg,jpg.  If you are using chrome, right click the background and select inspect element.  Select the console tab and see if there's an issue loading the image (error 404).

**Comment by KenCope** [comment]
Failure to load. bg.jpg not found. But that file is in there. I’ve even tried a few different .jpg files.  Frustrated :-/

Ken[Image]


________________________________

**Comment by KenCope** [comment]
I’m an idiot!!  It can’t find bg.jpg when I have the file names bp.jpg!  Thanks to all for your help! I’ll consider this case closed. Happy holidays.

Ken

________________________________
