### ISSUE TITLE
cannot load any ADD-ON

### ISSUE THREAD

**Issue by mmillebr** [Manuel83/craftbeerpi3#161]
when i try to download a new ADD-ON and restart the CBPi, it shows me an error message like this:
Failed to load plugin PIDBoil
__init__() got an unexpected keyword argument 'description'
Any idea ?

**Comment by HooTsBrooklyn** [comment]
What version of CBPi are you running? 3.0, Master Branch, or 3.1_Alpha?

**Comment by mmillebr** [comment]
CraftBeerPi v3.0

**Comment by HooTsBrooklyn** [comment]
3.0 is broken, you should switch back to the Master Branch.  Click Settings, Select Settings, then scroll to the bottom.  Click Activate above the Master Branch option.  Then restart the Pi.

**Comment by mmillebr** [comment]
Perfect !! It´s working ... thank you !
