### ISSUE TITLE
No entry in sensor list

### ISSUE THREAD

**Issue by fencerJP** [Manuel83/craftbeerpi3#162]
I'm installing cbpi3 for the first time, so I apologize if I've made a mistake somewhere. I THINK I have the DS1820 one wire sensor wired up correctly (per http://web.craftbeerpi.com/hardware/ ), but I can't get the temperature to display in cbpi3.

On my main page, I get 0 deg:
![1](https://user-images.githubusercontent.com/33802486/33795931-fbd813c4-dd2d-11e7-88d0-e3c62ceb4c7d.png)

While in my hardware setup, I get:
![2](https://user-images.githubusercontent.com/33802486/33795933-08f17cc6-dd2e-11e7-8e6f-237d68b0d25e.png)

I expected something like this, from the setup video:
![3](https://user-images.githubusercontent.com/33802486/33795978-f94fc3d0-dd2e-11e7-8210-93021b3e205f.png)

When I run `ls /sys/bus/w1/devices/` in terminal, I get nothing. Is there a package that I need to install? What am I doing wrong?

**Comment by HooTsBrooklyn** [comment]
Have you rebooted the Pi with the sensor connected?  I noticed that mine didn't show up in the list until I had them connected when the CBPi service started.  Once I had them setup, I could connect/disconnect them at will.

**Comment by fencerJP** [comment]
Well now I suspect something with my GPIO overall. Today I attempted to just turn on/off an SSR, and was unable to do so, despite testing two different SSRs, attaching the SSR to the 3v3 pin 1, and reconfiguring  the pins vs GPIO numbers (because pin 12 is GPIO18, but the settings were unclear which one number it was referring to). 

I will find a way to test the SSRs, but is it possible to have a faulty GPIO? Is there some way to test it besides using a multimeter? The Pi itself obviously works.

**Comment by lalo-uy** [comment]
Som SSr do not triger with 3V.
Try them witn 5V.
Try the GPIO with a led + 150 ohms R

2017-12-23 3:28 GMT-03:00 fencerJP <notifications@github.com>:

**Comment by fencerJP** [comment]
Well after a re-install and a re-wire, I'm not sure what the issue was. Everything APPEARS to be working during a bench test, but we'll see how it goes when I put everything in the box.
