### ISSUE TITLE
CBPi3 Plugins - Where'd they go?

### ISSUE THREAD

**Issue by KenCope** [Manuel83/craftbeerpi3#168]
I just reinstalled CBPi and I see the plugin __init__.py file is empty.  Is there a fix or something I'm missing?  The plugins always worked for me before.  Thanks.

**Comment by HooTsBrooklyn** [comment]
Looks like the plugins repository broke yesterday.
https://github.com/Manuel83/craftbeerpi-plugins

**Comment by ksullivan86** [comment]
Is this still an issue? I did a fresh install and now I don't see any plugins load when I go to the plugins page not sure what to do, any ideas?

**Comment by cpompermaier** [comment]
Same problem here. I just installed and had no errors during installation.

**Comment by HooTsBrooklyn** [comment]
It should be good now.  One of the added plugins had a small issue that was fixed.

**Comment by cpompermaier** [comment]
Thank you. Working good now.

**Comment by ckrack** [comment]
@KenCope please close the issue.
