### ISSUE TITLE
Timer Buzzer

### ISSUE THREAD

**Issue by KenCope** [Manuel83/craftbeerpi3#169]
I might just be missing it, but I have an external buzzer that is 240V connected to a relay.  I'd like to activate that relay when each step timer is complete.  Can anyone help?  Regards to all.

**Comment by HooTsBrooklyn** [comment]
I'd use the plugin [ToggleStep](https://github.com/IndyJoeA/cbpi_ToggleStep).
Setup the buzzer as an actor and have it activated via the ToggleStep plugin.

**Comment by Philusha1983** [comment]
I use external buzzer and a toggle step too.
I trigger the buzzer when I need to add grains.
