### ISSUE TITLE
installed plugin do not show up in the system

### ISSUE THREAD

**Issue by LucLN** [Manuel83/craftbeerpi3#190]
Hi,
I have an issue with plugin .. after installing new plugin they don't show up in the system, even not after a reboot.
Does anyone have a solition for this?
Thanks.

**Comment by lalo-uy** [comment]
Try not to autostart CBP but go to CBI folder and run    ./run.py
That way you can see the init messages. may be some thing is not set ok

2018-05-15 6:44 GMT-03:00 LucLN <notifications@github.com>:

**Comment by LucLN** [comment]
no answer from the developer ..
