### ISSUE TITLE
Recipe Export

### ISSUE THREAD

**Issue by TiagoNetoPT** [Manuel83/craftbeerpi3#192]
Hello.

I've created my own steps, due to the addition of several valves to the system.
How can I export those steps as recipe?

**Comment by jonrhall** [comment]
Hi @TiagoNetoPT, I don't think that's a current feature of CraftBeerPi3. Wouldn't be hard to write an extension that converts the data located at `http://<<your-cbpi-server>>/api/step` into BeerXML-compatible format, but that's not something that I've seen done yet.

**Comment by TiagoNetoPT** [comment]
Hi @jonrhall . I've just ask because V2.2 had that option I think.

**Comment by jonrhall** [comment]
Ah OK, that makes sense. I forgot that 2.x had that feature, I don't think 3 does yet.
