### ISSUE TITLE
Update to 3.1

### ISSUE THREAD

**Issue by TiagoNetoPT** [Manuel83/craftbeerpi3#193]
Hello.

I've been trying to update to version 3.1.

Already download zip file and run install.sh. Also tried to activate it from system menu.
But nothing happen.

Can anyone help me please?

**Comment by jonrhall** [comment]
@TiagoNetoPT I'm pretty sure 3.1 is marked as an Alpha release, as such it can be unstable to use and I don't believe it's the officially supported version (most people seem to be running 3.0). I would stick with 3.0 until further notice if I were you.
