### ISSUE TITLE
Method not allowed - Recipe

### ISSUE THREAD

**Issue by TiagoNetoPT** [Manuel83/craftbeerpi3#195]
Hello.

I've using Craftbeerpi 3.0V and already created some plugins according to what I need.

I was looking for recipe import ( craftbeerpi3/modules/recipe_import/restapi.py)  and I got this message:

![image](https://user-images.githubusercontent.com/13378465/40513431-a7cd8a1e-5f9d-11e8-9765-79c8c2225030.png)

The URL I used was: http://192.168.1.72:5000/api/recipe/import/v1/

And I was trying to use this info from Wiki:
https://github.com/Manuel83/craftbeerpi3/wiki/Recipe-REST-API

What I'm doing wrong?

**Comment by lalo-uy** [comment]
You need to do a POST request instead og a GET as the browser do for default

2018-05-24 18:52 GMT-03:00 TiagoNetoPT <notifications@github.com>:
