### ISSUE TITLE
Brewstep list missing info

### ISSUE THREAD

**Issue by Blom1974** [Manuel83/craftbeerpi3#2]
List when editing brewsteps is missing info in State, Start, End columns.
![image](https://user-images.githubusercontent.com/9973750/27013481-e947477a-4ee4-11e7-837d-f07220c6a22c.png)

**Comment by Blom1974** [comment]
Probably by design. Shows when active. Thought it would show the timer and temp setting for each step as configured.

**Comment by Manuel83** [comment]
Shown when active or finished
