### ISSUE TITLE
alternatives for wiringPi

### ISSUE THREAD

**Issue by perlporter** [Manuel83/craftbeerpi3#231]
git.drogon.net is temporarily unavailable. Please look for alternatives for wiringPi, etc. -Gordon
http://wiringpi.com/wiringpi-deprecated/

**Comment by Manuel83** [comment]
Valid point! Any suggestion for an alternative?

**Comment by perlporter** [comment]
Unfortunately no, I'm sorry if I expressed myself the wrong way.
They are words of the creator, not mine ...
I'm just reporting because I can't do a new install.

**Comment by Manuel83** [comment]
The question is whether wiringpi is really required. Did you try to select "No" for wiringpi during the installation?

**Comment by perlporter** [comment]
No I did not try.
Good to know, I will do the installation doing what you recommended.
I thought it was necessary to have wiringPi installed for the proper functioning of craftbeerPi.

**Comment by Manuel83** [comment]
It’s working?

**Comment by perlporter** [comment]
The installation was completed successfully. 
But I haven't tested it yet
