### ISSUE TITLE
Cannot get auto to start heating

### ISSUE THREAD

**Issue by Blom1974** [Manuel83/craftbeerpi3#3]
Brewstep is started and kettle is in auto mode but heater does not start.

![image](https://user-images.githubusercontent.com/9973750/27013510-b7978400-4ee5-11e7-9bc5-3c4196ec4af3.png)

**Comment by Blom1974** [comment]
It was some problem with actuator not saved on kettle.

**Comment by Manuel83** [comment]
Can you post a picture of your hardware settings, please. Including a picture of your kettle config

**Comment by Blom1974** [comment]
I think this was an human error. I saved a kettle with an actuator for heat. But then i deleted and and made a new actuator which in turn made the kettle actuator to be empty.

It might be good to have som form of check. Not not really sure of how though.
Warning when deleting actuator which is in use? "this actuator is used in kettle x and kettle y.
