### ISSUE TITLE
Feature request: Sensor bias

### ISSUE THREAD

**Issue by helibrewer** [Manuel83/craftbeerpi3#33]
The ability to add(subtract) a bias value to allow for slight differences in sensor value readings (temp sensor calibration).

**Comment by JamFfm** [comment]
This would be helpful because I used an Offset of 0.4 in one of my temp sensores

**Comment by carlallen** [comment]
I made a pull request to add this feature, if that doesn't get accepted I also made a plugin that does teh same thing: https://github.com/carlallen/cbpi_BiasedOneWireSensor
