### ISSUE TITLE
Fermentation dosen´t take decimals?

### ISSUE THREAD

**Issue by Ahoybakk** [Manuel83/craftbeerpi3#35]
Hey.

I tried to configure a fermentation last night, and i couldn't get it to work properly. Here is my setup, can anyone tell me why?

It´s prob something wrong with my setup.

<img width="483" alt="skjermbilde 2017-06-20 kl 23 05 13" src="https://user-images.githubusercontent.com/29613911/27405746-1c02fc2c-56d3-11e7-86ba-12a4ea81182d.png">

**Comment by JamFfm** [comment]
What happens if you use 0.1 etc instead of 0,1?

**Comment by Ahoybakk** [comment]
Same thing then...

**Comment by carlallen** [comment]
That's just how it is.

**Comment by carlallen** [comment]
but, I made a pull request for you anyway
