### ISSUE TITLE
Hardware Setup Not Recognized

### ISSUE THREAD

**Issue by beer4me** [Manuel83/craftbeerpi3#37]
<<Need to set up a fermenter>>

**Comment by swimIan** [comment]
I think you have to add a fermentor with the switches and sensors associated with it.

**Comment by beer4me** [comment]
Yep.  I watched the video closely and figured that out... goofy setup process... wanted an 'Actor' and a 'cooler'??  I'm running my fermentation chambers with a sensor for beer (in a thermowell) for control to heat or cool (season dependent) and another sensor to monitor a second beer or chamber temp - the 3.0 setup made no sense.  Also, setting up a fermentation session was much more cumbersome than 2.2... went back to 2.2...  Thanks for the reply. (I tried to delete this issue, but I'm new to github...)
