### ISSUE TITLE
Kettle frame for  boiling

### ISSUE THREAD

**Issue by AHm74** [Manuel83/craftbeerpi3#42]
Would it be possible to adapt a kettle frame for boilers? When boiling or taking the liquid to boil the temperature is not that interesting, the power is what I want to see and control.

Right now I'm using the target temperature to control the power to the boil (named temperature but controlling power) top right on the picture.

It would be nice if it was possible.

![bild](https://user-images.githubusercontent.com/4309313/27516839-d5822c36-59c1-11e7-959e-349b7d883bb5.png)

**Comment by jalim** [comment]
Does the latest UI fix your request?  Power is now shown alongside the heater for the kettle.

<img width="348" alt="kettle" src="https://user-images.githubusercontent.com/6856386/27769806-86f345c8-5f75-11e7-9fb9-a100d256396f.png">

**Comment by Manuel83** [comment]
Should be available now

**Comment by AHm74** [comment]
Well, yes. This will for sure do it. For me the temperature is not really interesting at all while boiling. The boiling part is primarily a matter of setting the power to get to boil and after that to be able to control the boiling to a "good rolling boil".
