### ISSUE TITLE
donation_notification does not exist in parameters

### ISSUE THREAD

**Issue by helibrewer** [Manuel83/craftbeerpi3#46]
from craftbeerpi3.modules.notification.__init__.py

donation_notification does not exist in System->Parameters

**Comment by jalim** [comment]
This is an issue with the database between updates.  You need to delete the database so that it can be rebuilt and the donation parameter will be added to the new database.

**Comment by helibrewer** [comment]
Thank you, I missed that, works fine

**Comment by swimIan** [comment]
Do I just send the database to the recycle bin?
