### ISSUE TITLE
Fermenter sensors

### ISSUE THREAD

**Issue by MikonosII** [Manuel83/craftbeerpi3#51]
The fermenter cooling only works if there is sensors loaded in all three spots.

**Comment by Manuel83** [comment]
Only the first sensor is use for the control logic the other are optional

**Comment by MikonosII** [comment]
Yep I've got that, but the control only worked after all sensors were all the same and a dummy actor was placed for the heater

**Comment by MikonosII** [comment]
Closing issue as this was operator error.
