### ISSUE TITLE
Buzzer Not Working

### ISSUE THREAD

**Issue by Mrpond1970** [Manuel83/craftbeerpi3#52]
I can't get the buzzer to work with my Craftbeerpi board. set the buzzer up on GPIO 20 and nothing happens during the steps process. I have set the buzzer up as an Actor and when pressing the on screen button it works.

**Comment by swimIan** [comment]
Same problem for me. Do the steps need to be rewritten to include a buzzer?

**Comment by jalim** [comment]
Not all of the steps include notifications of step completion.  Some do and others don't.  Are you finding that it never beeps or just that it doesn't beep as the steps progress?

**Comment by Mrpond1970** [comment]
I find that it never beeps

**Comment by jalim** [comment]
Can you download your app.log and have a look for mentions of buzzer?  If it's having trouble there should be a log entry both showing which GPIO pin its trying to use and wether it is failing.

**Comment by Mrpond1970** [comment]
Very Large App.log 66k

**Comment by jalim** [comment]
If you do a search for any mentions of buzzer, should be easy to find a few.

**Comment by Mrpond1970** [comment]
/home/pi/craftbeerpi3/modules/buzzer/__init__.py: 
2017-06-26 20:47:26,190 - INFO - INIT BUZZER NOW GPIO16
2017-06-26 20:47:26,191 - INFO - BUZZER SETUP OK
2017-06-26 20:47:26,191 - INFO - INIT OK
2017-06-26 20:47:26,192 - INFO - INITIALIZER - METHOD init PAHT 

Looks like GPIO16 being used but i have selected GPIO20 in the front end as my PI Board uses 20 for the buzzer

**Comment by jalim** [comment]
Ah ok, have found the bug.  It appears that it's trying to read the buzzer setting before the setting has been loaded so it's just defaulting to 16.  I will have a play around and create a fix if I can.

**Comment by Mrpond1970** [comment]
Great stuff thanks Jalim

**Comment by jalim** [comment]
I have submitted a fix for Manuel to action when he gets a chance.

**Comment by carlallen** [comment]
did the fix solve the problem?

**Comment by fekeese** [comment]
Yesterday I installed a new version of 3 and the buzzer stopped, I was using the craftbeerpi 3 for two weeks and everything was perfect before that.

Wiring -  BUZZER on GPIO16 like default  :( it never beeps

**Comment by jalim** [comment]
Check the parameters page has it set to 16.  There was a bug where it was defaulting to 16 no matter what was selected which has been fixed so now you'll need to select 16.

**Comment by swimIan** [comment]
I brewer today with a fresh update. My buzzer on 20 did not beep at any point.

**Comment by helibrewer** [comment]
I don't use a buzzer, but I do see an ERROR message for the buzzer in my log.
[app.txt](https://github.com/Manuel83/craftbeerpi3/files/1133835/app.txt)

**Comment by fekeese** [comment]
Same as mine :(

**Comment by swimIan** [comment]
Should line 16 be "gpio=self.gio" or should it be "gpio=int(self.gpio)" as it was in version 2.2?
