### ISSUE TITLE
Step plugins not able to utilize a Select Property

### ISSUE THREAD

**Issue by IndyJoeA** [Manuel83/craftbeerpi3#61]
I am writing a Step plugin, and when I try to create a Property.Select, it is being ignored by the GUI.  To make sure I was not just creating a bad plugin with some other mistake, I modified a built-in step (MashStep) and just added the following code, and it too was being ignored:

```python
select_field = Property.Select("Selection", options=["One", "Two", "Three"])
```

This same code works fine if it is used in a Sensor plugin.

**Comment by Manuel83** [comment]
You try to use 

`StepProperty.Select`

**Comment by IndyJoeA** [comment]
I have just tried that and it did not work either.  However, Carl's pull request did fix it.
