### ISSUE TITLE
Charts not showing up

### ISSUE THREAD

**Issue by adrianoftyriel** [Manuel83/craftbeerpi3#79]
Temperature charts show up blank.

I've updated to the most recent version, tried with multiple browsers on multiple devices (including my Pi3, cell phone, PC), all still show up just white, no detail.

**Comment by jalim** [comment]
Have you tried deleting your old log files?  This can be done from the user interface, then restart your Pi.

**Comment by adrianoftyriel** [comment]
Thank you, someone pointed that out to me last night and it resolved the issue. File this one under PEBCAK or id10t errors.
