### ISSUE TITLE
Enhancement Adding Cycle lenght to GPIOPWM

### ISSUE THREAD

**Issue by Blom1974** [Manuel83/craftbeerpi3#8]
It is nice to have an cycle lenght option on the GPIOPWM. For example an SSR with zero crossing start might not work good with very short periods. Then you might for example set cycle lenght to 10 sec and then modulate the time 0-100% of that.

**Comment by hjarupBrewDK** [comment]
I have the same observation and measurement. I my view a sensible period is >6sec. 
This will also make it usefull if using mechanical relays.

(see attached Picture of Measurement on PIO from RPI)
![issue_pwm_period](https://user-images.githubusercontent.com/26488979/27034176-beab726e-4f7c-11e7-9334-a38b3969bc9c.png)

**Comment by Blom1974** [comment]
Nice explanation!

**Comment by seesser** [comment]
When I made invertPWM I built it off the GPIOPWM.  When you setup the Actor under Duty Cycle is actually the frequency Cycle.  So just change the duty cycle to what you want the frequency cycle to be.  Power under the main screen is then the Duty Cycle or percent of the cycle it is on.  I will add the Duty Cycle name as a bug report.
