### ISSUE TITLE
No Beep beween Mash Steps

### ISSUE THREAD

**Issue by JamFfm** [Manuel83/craftbeerpi3#97]
There is a beep of the buzzer after reaching temp of Mash in step, but from Mash step to the next there is no beep. 
Got beep after updates or at the reboot. Love that.
It would be better with beeps beween Mashstaps so i do know that the next step starts without watching any Screen.

**Comment by swimIan** [comment]
Does it beep when the timer elapses?

**Comment by JamFfm** [comment]
no it does not beep when the timer elapses. This is the point.

**Comment by swimIan** [comment]
I think a line needs to be added to the mash step to get the the additional beeps. Would you want the mash step to beep when it's a temperature (helpful for step mashing) and/or at the conclusion of the timer? Would you want the boilstep to beep in a similar manner (at temp, hop alerts, and at conclusion)?

**Comment by swimIan** [comment]
I found the line to add and tested it. I'll create a pull request shortly. Stay tuned.

**Comment by swimIan** [comment]
https://github.com/Manuel83/craftbeerpi3/pull/98

**Comment by JamFfm** [comment]
The beep shouls appear at the end of the mashstep this would be the same as end of timer.

**Comment by swimIan** [comment]
The pull request does add the beep at the end of the mash step

**Comment by JamFfm** [comment]
perfect, sorry did not know that notification is combined with beep. 
Thanks for your work in this comunity

**Comment by JamFfm** [comment]
Works for me. Leave it some days open in case someone has got an issue.

**Comment by JamFfm** [comment]
Works so far. Does not beep when timer starts. But his is ok. Just want to mention in case someone says it is a failure.
